version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo_nest_pokemon
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: nest-pokemon
